// Banco de dados local isolado dos componentes
export const housesData = [
  {
    id: 1,
    title: "Apartamento Grande",
    location: "Vitória - ES",
    description: "Bairro Nobre, Vista para o Mar",
    oldPrice: "3.000",
    price: "2.200",
    img: "assets/1.jpg",
    area: 100,
    rooms: 2,
    bathrooms: 2,
  },
  {
    id: 2,
    title: "Apartamento Praia",
    location: "Guarapari - ES",
    description: "Frente para o mar, excelente localização",
    oldPrice: "5.000",
    price: "3.200",
    img: "assets/2.jpg",
    area: 100,
    rooms: 4,
    bathrooms: 3,
  },
  {
    id: 3,
    title: "Apartamento Luxo",
    location: "Vila Velha - ES",
    description: "Alto padrão com acabamento fino",
    oldPrice: "4.000",
    price: "2.800",
    img: "assets/3.jpg",
    area: 100,
    rooms: 3,
    bathrooms: 2,
  },
  {
    id: 4,
    title: "Apartamento Lazer",
    location: "Serra - ES",
    description: "Área de lazer completa para toda a família",
    oldPrice: "3.500",
    price: "2.560",
    img: "assets/4.jpg",
    area: 90,
    rooms: 2,
    bathrooms: 2,
  },
  {
    id: 5,
    title: "Apartamento Residencial",
    location: "Itaparica - ES",
    description: "Segurança 24h e ótima infraestrutura",
    oldPrice: "5.500",
    price: "3.560",
    img: "assets/5.jpg",
    area: 100,
    rooms: 3,
    bathrooms: 3,
  },
  {
    id: 6,
    title: "Apartamento Novo",
    location: "Laranjeiras - ES",
    description: "Pronto para morar, recém-construído",
    oldPrice: "4.500",
    price: "3.600",
    img: "assets/6.jpg",
    area: 90,
    rooms: 3,
    bathrooms: 2,
  },
];
